# 1) To use requests in this file, you need to install the REST Client extension in Visual Studio Code
#
# 2) In the settings.json of the REST Client extension, add these environment variables like so:
# "rest-client.environmentVariables": {
#         "$shared": {
#             "path-to-data": "./fsh-generated/resources/"
#         },
        "poc-vws-gf": {
            "org1-fhir-url": "http://fhir-org1.test.dataverloskunde.nl/fhir/",
            "org1-orca-url": "http://orca-org1.test.dataverloskunde.nl/cpc/cps/fhir/",
            "org1-access-token": "Bearer helsinki",
            "org2-fhir-url": "http://fhir-org2.test.dataverloskunde.nl/fhir/",
            "org2-access-token": "Bearer your-token-here",
            "org3-fhir-url": "http://fhir-org3.test.dataverloskunde.nl/fhir/",
            "org3-access-token": "Bearer your-token-here",
            "org4-fhir-url": "http://fhir-org4.test.dataverloskunde.nl/fhir/",
            "org4-access-token": "Bearer your-token-here",
        }
# }
# 
# 3) Switch between environments by clicking on the environment name in the status bar at the bottom right of the window


### POST data of services in EHR of Organization 1

POST {{org1-orca-url}}
Content-Type: application/fhir+json
Authorization: {{org1-access-token}}

<@ {{path-to-data}}Bundle-services-phi-organization1.json

### POST existing data in EHR of Organization 2

POST {{org2-fhir-url}}
Content-Type: application/fhir+json
Authorization: {{org2-access-token}}

<@ {{path-to-data}}Bundle-services-phi-organization2.json


### POST existing data in EHR of Organization 3


POST {{org3-fhir-url}}
Content-Type: application/fhir+json
Authorization: {{org3-access-token}}

<@ {{path-to-data}}Bundle-services-phi-organization3.json

### POST existing data in EHR of Organization 4


POST {{org4-fhir-url}}
Content-Type: application/fhir+json
Authorization: {{org4-access-token}}

<@ {{path-to-data}}Bundle-services-phi-organization4.json